#!/bin/bash

# Backupscript: Erstellen und Zurückspielen von Backup Verzeichnissen
# Author : Niklas Haag
# E-Mail : haagni@elektronikschule.de
# Version: v1.0

# Hauptmenu ausgeben
function menu(){
	clear
	echo "|----------------------------------------------|"
	echo "| Hauptmenu:                                   |"
	echo "|                                              |"
	echo "|      Backup erstellen:      B                |"
	echo "|      Inhalt eines Backups:  L                |"
	echo "|      Backup zurück spielen: R                |"
	echo "|      Backup löschen:        D                |"
	echo "|      Programm beenden:      X                |"
	echo "|                                              |"
	read -p "| Eingabe: " EINGABE
}

# Eingeben der Kompressionsmethode
function compress(){
	clear
	echo "|----------------------------------------------|"
	echo "| Kompressionsmethode:                         |"
	echo "|                                              |"
	echo "|      ZIP:                   z                |"
	echo "|      BZIP2:                 j                |"
	echo "|      XZ:                    J                |"
	echo "|                                              |"
	read -p "| Eingabe: " COMPRESS
}

# Eingeben des Backuppfades
function where2Backup(){
	clear
	echo "|----------------------------------------------|"
	echo "| Wohin soll das Backup gespeichert werden:    |"
	echo "|                                              |"
	read -p "| Eingabe: " WHERE2BACKUP 
}

# Eingeben des Pfades, der gesichert werden soll
function what2Backup(){
	clear
	echo "|----------------------------------------------|"
	echo "| Wohin soll das Backup gespeichert werden:    |"
	echo "|                                              |"
	read -p "| Eingabe: " WHAT2BACKUP 
}

function where2find(){
		clear
		echo "|------------------------------------------|"
		echo "| Backup löschen	                         |"
		echo "|------------------------------------------|"
		echo "| In welchem Ordner soll das Backup gesucht|"
		echo "| werden?                                  |"
		read -p "|Eingabe: " WHERE2FIND
}

function what2find(){
	echo "|------------------------------------------------------------------------------------------|"
	echo "| Backup löschen	                                                                         |"
	echo "|------------------------------------------------------------------------------------------|"
	echo "| Nach welchen Dateien soll gesucht werden (korrekte Dateiendung                           |"
	read -p "| Eingabe: " WHAT2FIND
}

function what2delete(){
	echo "|------------------------------------------------------------------------------------------|"
	echo "| Backup löschen	                                                                         |"
	echo "|------------------------------------------------------------------------------------------|"
	echo "| Welches Backup soll gelöscht werden                                                      |"
	read -p "| Eingabe: " WHAT2DELETE
	
	echo rm /$WHERE2FIND/WHAT2DELETE
}

function backup(){
	BACKUPFILE=$(date +%Y%m%d-%H%M%S)-backup.tgz
	YESNO=0
	until [ $YESNO = 1 ]
	do
		compress
		echo "|-----------------------------------------------------------------------------------|"	
		echo "| Sind Sie sicher das Sie die Option ${COMPRESS}                                    |" 
		echo "| benutzen möchten?                                                                 |"
		read -p "| (0: nein | 1: ja) " YESNO
	done
	# 
	YESNO=0
	until [ $YESNO = 1 ]
	do
		where2Backup
		echo "|-----------------------------------------------------------------------------------|"
		echo "| Sind Sie sicher das Sie hier in speichern möchten: ${WHERE2BACKUP}                |" 
		echo "| benutzen möchten?                               			          |"
		read -p "| (0: nein | 1: ja) " YESNO
	done
	#
	YESNO=0
	until [ $YESNO = 1 ]
	do
		what2Backup
		echo "|-----------------------------------------------------------------------------------|"
		echo "| Sind Sie sicher das Sie dieses Verzeichnis sichern wollen? ${WHAT2BACKUP}         |" 
		echo "| benutzen möchten?                                                                 |"
		read -p "| (0: nein | 1: ja) " YESNO
	done
		
	tar cf${COMPRESS} ${WHERE2BACKUP}/$BACKUPFILE ${WHAT2BACKUP}
	sleep 2
}

function unbackup(){
	echo "UNBACKUP"
}

function listbackup(){
	echo "LISTBACKUP"
}

function deletebackup(){
	YESNO=0
	until [ $YESNO = 1 ]
	do
		where2find
		echo "|-----------------------------------------------------------------------------------|"
		echo "| Sind Sie sicher das Sie in diesem Verzeichnis suchen wollen? ${WHERE2FIND}        |" 
		echo "| benutzen möchten?                                                                 |"
		read -p "| (0: nein | 1: ja) " YESNO
	done
	
	YESNO=0
	until [ $YESNO = 1 ]
	do
		what2find
		echo "|-----------------------------------------------------------------------------------|"
		echo "| Sind Sie sicher das Sie nach diesen Dateien suchen wollen? ${WHAT2FIND}           |" 
		echo "| benutzen möchten?                                                                 |"
		read -p "| (0: nein | 1: ja) " YESNO
	done
	
	echo "find /${WHERE2FIND} -name *.${WHAT2FIND}" 
	
	YESNO=0
	until [ $YESNO = 1 ]
	do
		what2delete
		echo "|-----------------------------------------------------------------------------------|"		
		echo "| Sind sie sicher, dass Sie dieses Backup löschen wollen §{WHAT2DELETE}             |"
		read -p "| (0: nein | 1: ja) " YESNO
	done
	
}

# Hauptereignisschleife
while :
do
	menu
	case $EINGABE in
		b|B)
			backup
			;;
		r|R)
			unbackup
			;;
		l|L)
			listbackup
			;;
		d|D)
			deletebackup
			;;
		*)
			echo "Und Tschüss"
			exit 1
	esac
	sleep 2
done

exit 0
